version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=wallet
    ports:
      - '3306:3306'
    volumes:
      - './data:/var/lib/mysql'