version: '3'
services:
  mongo:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=wallet
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
    ports:
      - '27017:27017'
    volumes:
      - './data:/data/db'