createdUser:
  handler: src/functions/user/handler.create
  iamRoleStatementsInherit: true
  events:         
    - http:
        path: /users
        method: post
        cors: true
        request:
          schema:
            application/json: ${file(src/schemes/user.scheme.json)}
        authorizer: authorizerFunc
createdOrder:
  handler: src/functions/order/handler.create
  iamRoleStatementsInherit: true
  events:         
    - http:
        path: /orders
        method: post
        cors: true
        request:
          schema:
            application/json: ${file(src/schemes/order.scheme.json)}
        authorizer: authorizerFunc
increaseBalance:
  handler: src/functions/user/handler.increaseBalence
  iamRoleStatementsInherit: true
  events:         
    - http:
        path: /users/icnrease-balance
        method: post
        cors: true
        request:
          schema:
            application/json: ${file(src/schemes/userIncrease.scheme.json)}
        authorizer: authorizerFunc
transfer:
  handler: src/functions/user/handler.transfer
  iamRoleStatementsInherit: true
  events:         
    - http:
        path: /users/transfer
        method: post
        cors: true
        request:
          schema:
            application/json: ${file(src/schemes/userIncrease.scheme.json)}
        authorizer: authorizerFunc
authorizerFunc:
  handler: src/authorizer/auth.authorizerFunc