createdUser:
  handler: src/functions/user/handler.create
  iamRoleStatementsInherit: true
  events:         
    - http:
        path: /users
        method: post
        cors: true
        request:
          schema:
            application/json: ${file(src/squemes/user.squema.json)}
        authorizer: authorizerFunc
createdOrder:
  handler: src/functions/order/handler.create
  iamRoleStatementsInherit: true
  events:         
    - http:
        path: /orders
        method: post
        cors: true
        request:
          schema:
            application/json: ${file(src/squemes/order.squema.json)}
        authorizer: authorizerFunc
increaseBalance:
  handler: src/functions/user/handler.increaseBalence
  iamRoleStatementsInherit: true
  events:         
    - http:
        path: /users/icnrease-balance
        method: post
        cors: true
        request:
          schema:
            application/json: ${file(src/squemes/userIncrease.squema.json)}
        authorizer: authorizerFunc
authorizerFunc:
  handler: src/authorizer/auth.authorizerFunc