export const eventGenerator = ({ body }) => {
  const request = {
    body: body || '',
    headers: {
      'Content-Type': 'application/json',
      'User-Agent': 'PostmanRuntime/7.28.4',
      Accept: '*/*',
      'Cache-Control': 'no-cache',
      'Postman-Token': 'f8963a97-6387-43d3-b6e3-3c9d538c051d',
      Host: 'localhost:4000',
      'Accept-Encoding': 'gzip, deflate, br',
      Connection: 'keep-alive',
      'Content-Length': '141',
    },
    httpMethod: 'POST',
    isBase64Encoded: false,
    multiValueHeaders: {
      'Content-Type': ['application/json'],
      'User-Agent': ['PostmanRuntime/7.28.4'],
      Accept: ['*/*'],
      'Cache-Control': ['no-cache'],
      'Postman-Token': ['f8963a97-6387-43d3-b6e3-3c9d538c051d'],
      Host: ['localhost:4000'],
      'Accept-Encoding': ['gzip, deflate, br'],
      Connection: ['keep-alive'],
      'Content-Length': ['141'],
    },
    multiValueQueryStringParameters: null,
    path: '/users',
    pathParameters: null,
    queryStringParameters: null,
    requestContext: {
      accountId: 'offlineContext_accountId',
      apiId: 'offlineContext_apiId',
      authorizer: {
        claims: undefined,
        scopes: undefined,
        principalId: 'offlineContext_authorizer_principalId',
        userId: '2',
      },
      domainName: 'offlineContext_domainName',
      domainPrefix: 'offlineContext_domainPrefix',
      extendedRequestId: 'ckxiylchk0000pyvmhxv21dwz',
      httpMethod: 'POST',
      identity: {
        accessKey: null,
        accountId: 'offlineContext_accountId',
        apiKey: 'offlineContext_apiKey',
        apiKeyId: 'offlineContext_apiKeyId',
        caller: 'offlineContext_caller',
        cognitoAuthenticationProvider: 'offlineContext_cognitoAuthenticationProvider',
        cognitoAuthenticationType: 'offlineContext_cognitoAuthenticationType',
        cognitoIdentityId: 'offlineContext_cognitoIdentityId',
        cognitoIdentityPoolId: 'offlineContext_cognitoIdentityPoolId',
        principalOrgId: null,
        sourceIp: '127.0.0.1',
        user: 'offlineContext_user',
        userAgent: 'PostmanRuntime/7.28.4',
        userArn: 'offlineContext_userArn',
        clientCert: null,
      },
      path: '/users',
      protocol: 'HTTP/1.1',
      requestId: 'ckxiylchn0001pyvm5krl90ej',
      requestTime: '23/Dec/2021:07:46:33 -0500',
      requestTimeEpoch: 1640263593040,
      resourceId: 'offlineContext_resourceId',
      resourcePath: '/local/users',
      stage: 'local',
    },
    resource: '/users',
    stageVariables: undefined,
  };
  return request;
};
